/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Selvy_Recognizer */

#ifndef _Included_Selvy_Recognizer
#define _Included_Selvy_Recognizer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Selvy_Recognizer
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Selvy_Recognizer_initialize
  (JNIEnv *, jobject);

/*
 * Class:     Selvy_Recognizer
 * Method:    deinitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Selvy_Recognizer_deinitialize
  (JNIEnv *, jobject);

/*
 * Class:     Selvy_Recognizer
 * Method:    recognizer
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Selvy_Recognizer_recognizer
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
